


export const HANDLE_INCREMENT = 'HANDLE_INCREMENT';

export const HANDLE_DECREMENT = 'HANDLE_DECREMENT';

export const HANDLE_RESET = 'HANDLE_RESET';

export const HANDLE_INPUT_ONCLICK = 'HANDLE_INPUT_ONCLICK';

export const HANDLE_INPUT_ONCHANGE = 'HANDLE_INPUT_ONCHANGE';

export const HANDLE_TODO_ONSUBMIT = 'HANDLE_TODO_ONSUBMIT';

export const HANDLE_TODO_ONCHANGE = 'HANDLE_TODO_ONCHANGE';

export const HANDLE_TODO_EDIT = 'HANDLE_TODO_EDIT';

export const HANDLE_TODO_REMOVE = 'HANDLE_TODO_REMOVE'