

export const HANDLE_INCREMENT = 'HANDLE_INCREMENT';

export const HANDLE_DECREMENT = 'HANDLE_DECREMENT';

export const HANDLE_RESET = 'HANDLE_RESET';

export const HANDLE_NAME_CHANGE = 'HANDLE_NAME_CHANGE';

export const HANDLE_INPUT_CHANGE = 'HANDLE_INPUT_CHANGE';

export const HANDLE_DATA_SUCCESS = 'HANDLE_DATA_SUCCESS';

export const HANDLE_DATA_FAIL = 'HANDLE_DATA_FAIL';

export const HANDLE_DATA_START = 'HANDLE_DATA_START';

